// generator for f_out of my processor to show bad apple

#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>

const int FRAME_LEN = 3030;
const int BEGIN_VID = 2000;
const int NUM_FRAMES = 2181;

int main () {
    // this file was taken from https://github.com/Chion82/ASCII_bad_apple with small changes
    FILE *f_in = fopen ("badapple.txt", "r");
    FILE *f_out = fopen ("badapple.casm", "w");

    fprintf (f_out, "; This file is automatically generated to play bad apple on my cpu\n");

    char *buffer = (char*) calloc(FRAME_LEN + 1, sizeof (char));
    char *prev = (char*) calloc(FRAME_LEN + 1, sizeof (char));

    for (int frame = 0; frame < NUM_FRAMES; frame++) {
        fread (buffer, 1, FRAME_LEN, f_in);

        for (int i = 0; i <= FRAME_LEN; i++)
            if (!isspace (buffer[i])) 
                buffer[i] = 1;
            else 
                buffer[i] = 0;

        for (int i = 0; i <= FRAME_LEN; i++) {
            int diff = buffer[i] - prev[i];

            if (diff == 1) 
                fprintf (f_out, "push 1\npop [%d]\n", BEGIN_VID + i);
            else if (diff == -1)
                fprintf (f_out, "push 0\npop [%d]\n", BEGIN_VID + i);
        }

        // swap
        prev = (char*) ((size_t) prev ^ (size_t) buffer);
        buffer = (char*) ((size_t) prev ^ (size_t) buffer);
        prev = (char*) ((size_t) buffer ^ (size_t) prev);

        fprintf (f_out, "print\n\n\n");
    }

    free (buffer);
    free (prev);

    fclose (f_in);
    fclose (f_out);
}
